version: "3.8"

services:
  app:
    build: .
    image: boost-my-skills-bot:0.1
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    command: ["/app/wait-for-db.sh", "db", "5432", "/bin/main"]

  db:
    image: postgres:latest
    volumes:
      - ./app/dumps/bot_db_dump.sql:/docker-entrypoint-initdb.d/mydbdump.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  redis:
    image: redis:latest
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

volumes:
  pgdata:
    driver: local
