// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: app/pkg/proto/boost-bot.proto

package boost_bot_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateFrom int64 `protobuf:"varint,1,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	DateTo   int64 `protobuf:"varint,2,opt,name=dateTo,proto3" json:"dateTo,omitempty"`
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pkg_proto_boost_bot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_pkg_proto_boost_bot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_app_pkg_proto_boost_bot_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatisticsRequest) GetDateFrom() int64 {
	if x != nil {
		return x.DateFrom
	}
	return 0
}

func (x *GetStatisticsRequest) GetDateTo() int64 {
	if x != nil {
		return x.DateTo
	}
	return 0
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfosAdded int64 `protobuf:"varint,1,opt,name=infosAdded,proto3" json:"infosAdded,omitempty"`
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pkg_proto_boost_bot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_pkg_proto_boost_bot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_app_pkg_proto_boost_bot_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatisticsResponse) GetInfosAdded() int64 {
	if x != nil {
		return x.InfosAdded
	}
	return 0
}

var File_app_pkg_proto_boost_bot_proto protoreflect.FileDescriptor

var file_app_pkg_proto_boost_bot_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x6f, 0x6f, 0x73, 0x74, 0x2d, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x22, 0x37, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x41, 0x64,
	0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x41, 0x64, 0x64, 0x65, 0x64, 0x32, 0x6e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x12, 0x25, 0x2e, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x74,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x6f,
	0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x72, 0x69, 0x6c, 0x6c, 0x30, 0x39, 0x30, 0x39, 0x2f, 0x62,
	0x6f, 0x6f, 0x73, 0x74, 0x2d, 0x6d, 0x79, 0x2d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x2d, 0x62,
	0x6f, 0x6f, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x5f, 0x62, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_pkg_proto_boost_bot_proto_rawDescOnce sync.Once
	file_app_pkg_proto_boost_bot_proto_rawDescData = file_app_pkg_proto_boost_bot_proto_rawDesc
)

func file_app_pkg_proto_boost_bot_proto_rawDescGZIP() []byte {
	file_app_pkg_proto_boost_bot_proto_rawDescOnce.Do(func() {
		file_app_pkg_proto_boost_bot_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_pkg_proto_boost_bot_proto_rawDescData)
	})
	return file_app_pkg_proto_boost_bot_proto_rawDescData
}

var file_app_pkg_proto_boost_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_pkg_proto_boost_bot_proto_goTypes = []interface{}{
	(*GetStatisticsRequest)(nil),  // 0: boost_bot_proto.GetStatisticsRequest
	(*GetStatisticsResponse)(nil), // 1: boost_bot_proto.GetStatisticsResponse
}
var file_app_pkg_proto_boost_bot_proto_depIdxs = []int32{
	0, // 0: boost_bot_proto.Statistics.GetStatistics:input_type -> boost_bot_proto.GetStatisticsRequest
	1, // 1: boost_bot_proto.Statistics.GetStatistics:output_type -> boost_bot_proto.GetStatisticsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_pkg_proto_boost_bot_proto_init() }
func file_app_pkg_proto_boost_bot_proto_init() {
	if File_app_pkg_proto_boost_bot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_pkg_proto_boost_bot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pkg_proto_boost_bot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_pkg_proto_boost_bot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_pkg_proto_boost_bot_proto_goTypes,
		DependencyIndexes: file_app_pkg_proto_boost_bot_proto_depIdxs,
		MessageInfos:      file_app_pkg_proto_boost_bot_proto_msgTypes,
	}.Build()
	File_app_pkg_proto_boost_bot_proto = out.File
	file_app_pkg_proto_boost_bot_proto_rawDesc = nil
	file_app_pkg_proto_boost_bot_proto_goTypes = nil
	file_app_pkg_proto_boost_bot_proto_depIdxs = nil
}
