// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: app/pkg/proto/boost-bot.proto

package boost_bot_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BostBotClient is the client API for BostBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BostBotClient interface {
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
}

type bostBotClient struct {
	cc grpc.ClientConnInterface
}

func NewBostBotClient(cc grpc.ClientConnInterface) BostBotClient {
	return &bostBotClient{cc}
}

func (c *bostBotClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, "/boost_bot_proto.BostBot/GetStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BostBotServer is the server API for BostBot service.
// All implementations must embed UnimplementedBostBotServer
// for forward compatibility
type BostBotServer interface {
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	mustEmbedUnimplementedBostBotServer()
}

// UnimplementedBostBotServer must be embedded to have forward compatible implementations.
type UnimplementedBostBotServer struct {
}

func (UnimplementedBostBotServer) GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedBostBotServer) mustEmbedUnimplementedBostBotServer() {}

// UnsafeBostBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BostBotServer will
// result in compilation errors.
type UnsafeBostBotServer interface {
	mustEmbedUnimplementedBostBotServer()
}

func RegisterBostBotServer(s grpc.ServiceRegistrar, srv BostBotServer) {
	s.RegisterService(&BostBot_ServiceDesc, srv)
}

func _BostBot_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BostBotServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/boost_bot_proto.BostBot/GetStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BostBotServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BostBot_ServiceDesc is the grpc.ServiceDesc for BostBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BostBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boost_bot_proto.BostBot",
	HandlerType: (*BostBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatistics",
			Handler:    _BostBot_GetStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/pkg/proto/boost-bot.proto",
}
